{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secret.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "secret.labels" . | nindent 4 }}
{{- if .Values.configMap.annotations }}
  annotations: {{ toYaml .Values.configMap.annotations | nindent 4 }}
{{- end }}
type: Opaque
{{- if .Values.secret.data }}
data:
{{- range $key, $value := .Values.secret.data }}
  {{ $key | nindent 2 }}: {{ $value | quote }}
{{- end }}
{{- end }}
{{- end }}
