{{- if .Values.deployment.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.deployment.serviceAccount.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "serviceAccount.labels" . | nindent 4 }}
{{- if .Values.deployment.serviceAccount.annotations }}
  annotations: {{ toYaml .Values.deployment.serviceAccount.annotations | nindent 4 }}
{{- end }}
{{- end }}
